policy:
  - template: ["request.yml"]
    section:
      - id: ["logo-category"]
        block-list: []
        label:
          - name: "service"
            keys: ["service"]
          - name: "original"
            keys: ["original"]
          - name: "unknown"
            keys: ["None", "unknown"]
      - id: ["permission"]
        block-list: ["None", "No"]
        label:
          - name: "permitted"
            keys: ["Yes"]
